### ISSUE TITLE
Mobileye M630 可以直接和周立功USBCANII型CAN卡物理连接么？

### ISSUE THREAD

**Issue by KevinYuk** [YYangjlu/Mobileye-M630-Data_Visualization#1]
Mobileye M630<---->USBCANII<---->PC
可以直接这样物理连接，并在pc上直接读取Mobileye M630的输出报文么？

不用实车，只用Mobileye M630，USBCANII，PC这3个物理硬件。

**Comment by YYangjlu** [comment]
不可以，M630必须要车速信号
